spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fastVideo
    username: root
    password: LRG@951089
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    format-sql: true

